### ISSUE TITLE
Multithreading in class Phylogeny_Tree

### ISSUE THREAD

**Issue by jmtsuji** [neufeld/AXIOME3#2]
Hi @danielm710 ,

Nice work on this pipeline. When running AXIOME3, I noticed that phylogenetic tree generation appears to happen with only one thread. I think tree generation is being managed by Class Phylogeny_Tree via the [`align-to-tree-mafft-fasttree`](https://docs.qiime2.org/2020.6/plugins/available/phylogeny/align-to-tree-mafft-fasttree/) pipeline of QIIME2. Given that phylogeny building can be computationally intensive, would it be possible to allow the `--p-n-threads` flag to be specified by the AXIOME3 user (e.g., as a parameter in the config file) to allow for multi-threading?

Thanks.

**Comment by danielm710** [comment]
For sure! Will also work on this sometime later this week
