### ISSUE TITLE
Export of rarefied table

### ISSUE THREAD

**Issue by jmtsuji** [neufeld/AXIOME3#3]
Hi @danielm710 ,

When I run AXIOME3, the exported rarefied table does not appear to be rarefied. I think I tracked down the issue.

Currently, the `requires` field of `class Convert_Rarefy_Biom_to_TSV` reads:
```
class Convert_Rarefy_Biom_to_TSV(luigi.Task):
    rarefy_export_dir = Output_Dirs().rarefy_export_dir

    def requires(self):
        return Filter_Feature_Table()
```

I think the last line above should be Rarefy(), like:
```
class Convert_Rarefy_Biom_to_TSV(luigi.Task):
    rarefy_export_dir = Output_Dirs().rarefy_export_dir

    def requires(self):
        return Rarefy()
```

Otherwise, AXIOME3 will export the filtered (but non-rarefied) table rather than the rarefied table. Does that make sense? I tried making this change on my end, and I seem to be getting the rarefied table as output now. But please check on your end to confirm (e.g., if you have a test dataset you commonly use).

Thanks for your work on AXIOME3.

**Comment by danielm710** [comment]
Hello @jmtsuji 

This is definitely a bug. Good observation. Thanks for reporting it, I'll fix this asap :)
